### PR TITLE
Fixing the prism highlighter issue

### PR DESCRIPTION
**Pull request by shidhincr**

### CODE REVIEW

**Comment by hemanth** [comment]
Better if we rename `my-features` to `js-features`

**Comment by shidhincr** [comment]
Agree.. But we already have `js-features.html` right ?

**Comment by shidhincr** [comment]
I guess better to name the existing `js-features.html` to `app.html` ( or similar, because it's the whole app-shell )  and rename `my-features` to `js-features`.

Wdyt ?

**Comment by hemanth** [comment]
or `js-feature` anything but `my-features` ;)

**Comment by shidhincr** [comment]
will rename to `js-feature` ( or `es-feature` ? )

**Pull request merged**
