### PR TITLE
Syntax highlighting with marked-element

### PR DESCRIPTION
**Pull request by shidhincr**
@hemanth I just made some workaround to make the syntax highlighting work. The code should not be merged.

I don't think that it's the right way to do syntax highlighting. First problem was since the polymer configuration is set to use `shadowDOM` none of the styles from prism.css will appear. So I had to include the theme css inside the custom element.

The above can be also solved by removing the `dom:shadow` from 

``` js
window.Polymer = {lazyRegister: true, dom: 'shadow'};
```

But the major problem is in code formatting. I saw the code blocks are set in the JSON file, and that causes the formatting issues. I guess, instead of setting the codes in a JSON file, we should use markdown files and load them using [marked-elements](https://elements.polymer-project.org/elements/marked-element). I guess this is something they have done in the polymer documentation website.

Let me see how they have done that.

### CODE REVIEW

**Comment by hemanth** [comment]
Yeah `window.Polymer = {lazyRegister: true, dom: 'shadow'};` is a workaround, could you please add `bower_components` to `.gitingnore` ?

`marked-elements` is the way to go! 

Feel free to manipulate the `data` dir as per need.

Thank you!

**Comment by hemanth** [comment]
I would love to hear what @robdodson would say about ^^

**Comment by shidhincr** [comment]
@hemanth Sure, I'll give the `marked-elements` a try.

I've added the `bower_components` to the .gitignore already. But, seems like you already pushed the `bower_components` directory to git -- which shows all those files in the diff.

Could you please remove them as well from your branch ? So, next time they won't be there in the diff.

**Comment by hemanth** [comment]
`git clean -xdn` must help you, anyway rebase it for now.

**Comment by shidhincr** [comment]
@hemanth Updated the PR. Please have a look

screen shot 2016-06-28 at 1 55 18 pm

**Comment by hemanth** [comment]
Cool, stuff!

Let us do the remaining as well and make the heading linkable as we discussed in slack.

**Comment by hemanth** [comment]
l41YrmD4Ze4jSYM4E

**Pull request merged**
